--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.470.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2021. 11. 29. 19:16:04
-- Server version: 10.4.17
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE jfitness;

--
-- Drop table `tbl_admin`
--
DROP TABLE IF EXISTS tbl_admin;

--
-- Drop table `tbl_orders`
--
DROP TABLE IF EXISTS tbl_orders;

--
-- Drop table `tbl_customers`
--
DROP TABLE IF EXISTS tbl_customers;

--
-- Drop table `tbl_payment`
--
DROP TABLE IF EXISTS tbl_payment;

--
-- Drop table `tbl_payment_method`
--
DROP TABLE IF EXISTS tbl_payment_method;

--
-- Drop table `tbl_products`
--
DROP TABLE IF EXISTS tbl_products;

--
-- Drop table `tbl_categories`
--
DROP TABLE IF EXISTS tbl_categories;

--
-- Drop table `tbl_nutriens`
--
DROP TABLE IF EXISTS tbl_nutriens;

--
-- Set default database
--
USE jfitness;

--
-- Create table `tbl_nutriens`
--
CREATE TABLE tbl_nutriens (
  nutrien_ID INT(11) UNSIGNED NOT NULL,
  carbohydrate INT(11) DEFAULT NULL,
  Fat INT(11) DEFAULT NULL,
  Protein INT(11) DEFAULT NULL,
  PRIMARY KEY (nutrien_ID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `tbl_categories`
--
CREATE TABLE tbl_categories (
  category_ID INT(11) UNSIGNED NOT NULL,
  category_name VARCHAR(100) DEFAULT NULL,
  image_name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (category_ID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `tbl_products`
--
CREATE TABLE tbl_products (
  product_ID INT(11) UNSIGNED NOT NULL,
  product_name VARCHAR(100) DEFAULT NULL,
  price DECIMAL(10, 2) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  image_name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (product_ID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE tbl_products 
  ADD CONSTRAINT category_id FOREIGN KEY (product_ID)
    REFERENCES tbl_categories(category_ID) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE tbl_products 
  ADD CONSTRAINT nutrient_id FOREIGN KEY (product_ID)
    REFERENCES tbl_nutriens(Nutrien_ID) ON DELETE NO ACTION;

--
-- Create table `tbl_payment_method`
--
CREATE TABLE tbl_payment_method (
  payment_method_ID INT(11) UNSIGNED NOT NULL,
  payment_method VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (payment_method_ID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create index `UK_tbl_payment_method_payment_method` on table `tbl_payment_method`
--
ALTER TABLE tbl_payment_method 
  ADD UNIQUE INDEX UK_tbl_payment_method_payment_method(payment_method);

--
-- Create table `tbl_payment`
--
CREATE TABLE tbl_payment (
  payment_ID INT(11) UNSIGNED NOT NULL,
  Creditcard_number INT(11) DEFAULT NULL,
  creditcard_expdate DATE DEFAULT NULL,
  cardholder_name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (payment_ID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE tbl_payment 
  ADD CONSTRAINT FK_tbl_payment_payment_ID FOREIGN KEY (payment_ID)
    REFERENCES tbl_payment_method(payment_method_ID) ON DELETE NO ACTION;

--
-- Create table `tbl_customers`
--
CREATE TABLE tbl_customers (
  customer_ID INT(11) UNSIGNED NOT NULL,
  username VARCHAR(100) DEFAULT NULL,
  password VARCHAR(100) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  phone_number INT(11) DEFAULT NULL,
  postal_code INT(11) DEFAULT NULL,
  country VARCHAR(255) DEFAULT NULL,
  city VARCHAR(15) DEFAULT NULL,
  Address VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY (customer_ID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `tbl_orders`
--
CREATE TABLE tbl_orders (
  order_ID INT(11) UNSIGNED NOT NULL,
  price DECIMAL(10, 2) DEFAULT NULL,
  quantity INT(11) DEFAULT NULL,
  order_date DATE DEFAULT NULL,
  PRIMARY KEY (order_ID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE tbl_orders 
  ADD CONSTRAINT customer_id FOREIGN KEY (order_ID)
    REFERENCES tbl_customers(customer_ID) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE tbl_orders 
  ADD CONSTRAINT product_id FOREIGN KEY (order_ID)
    REFERENCES tbl_products(product_ID) ON DELETE NO ACTION;

--
-- Create table `tbl_admin`
--
CREATE TABLE tbl_admin (
  ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  full_name VARCHAR(100) DEFAULT NULL,
  username VARCHAR(100) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

-- 
-- Dumping data for table tbl_nutriens
--
-- Table jfitness.tbl_nutriens does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_categories
--
INSERT INTO tbl_categories VALUES
(1, 'Feherjek', NULL),
(2, 'Kiegeszitok', NULL),
(3, 'Ruhazat', NULL);

-- 
-- Dumping data for table tbl_payment_method
--
INSERT INTO tbl_payment_method VALUES
(2, 'Bercsenyi Bank'),
(1, 'Jedlik Bank'),
(3, 'Revai Bank');

-- 
-- Dumping data for table tbl_products
--
-- Table jfitness.tbl_products does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_customers
--
INSERT INTO tbl_customers VALUES
(0, 'asd123', '1234', 'asd@gmail.com', 620, 8023, 'MagyarOrszag', 'Gyor', 'Tihanyi Arpad ut');

-- 
-- Dumping data for table tbl_payment
--
-- Table jfitness.tbl_payment does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_orders
--
-- Table jfitness.tbl_orders does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_admin
--
-- Table jfitness.tbl_admin does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;